//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 

namespace Reporter.XsdClasses.OnNkorschfdoppr
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Файл
    {

        private ФайлСвУчДокОбор свУчДокОборField;

        private ФайлДокумент документField;

        private string идФайлField;

        private ФайлВерсФорм версФормField;

        private string версПрогField;

        /// <remarks/>
        public ФайлСвУчДокОбор СвУчДокОбор
        {
            get {
                return this.свУчДокОборField;
            }
            set {
                this.свУчДокОборField = value;
            }
        }

        /// <remarks/>
        public ФайлДокумент Документ
        {
            get {
                return this.документField;
            }
            set {
                this.документField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл
        {
            get {
                return this.идФайлField;
            }
            set {
                this.идФайлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлВерсФорм ВерсФорм
        {
            get {
                return this.версФормField;
            }
            set {
                this.версФормField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог
        {
            get {
                return this.версПрогField;
            }
            set {
                this.версПрогField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлСвУчДокОбор
    {

        private ФайлСвУчДокОборСвОЭДОтпр свОЭДОтпрField;

        private string идОтпрField;

        private string идПолField;

        /// <remarks/>
        public ФайлСвУчДокОборСвОЭДОтпр СвОЭДОтпр
        {
            get {
                return this.свОЭДОтпрField;
            }
            set {
                this.свОЭДОтпрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдОтпр
        {
            get {
                return this.идОтпрField;
            }
            set {
                this.идОтпрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдПол
        {
            get {
                return this.идПолField;
            }
            set {
                this.идПолField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлСвУчДокОборСвОЭДОтпр
    {

        private string наимОргField;

        private string иННЮЛField;

        private string идЭДОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get {
                return this.наимОргField;
            }
            set {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get {
                return this.иННЮЛField;
            }
            set {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдЭДО
        {
            get {
                return this.идЭДОField;
            }
            set {
                this.идЭДОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ДокумТип
    {

        private string наимОснField;

        private string номОснField;

        private string датаОснField;

        private string допСвОснField;

        private string идФайлОснField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОсн
        {
            get {
                return this.наимОснField;
            }
            set {
                this.наимОснField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомОсн
        {
            get {
                return this.номОснField;
            }
            set {
                this.номОснField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаОсн
        {
            get {
                return this.датаОснField;
            }
            set {
                this.датаОснField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДопСвОсн
        {
            get {
                return this.допСвОснField;
            }
            set {
                this.допСвОснField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайлОсн
        {
            get {
                return this.идФайлОснField;
            }
            set {
                this.идФайлОснField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class НомСредИдТовТип
    {

        private string[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private string идентТрансУпакField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КИЗ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("НомУпак", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items
        {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдентТрансУпак
        {
            get {
                return this.идентТрансУпакField;
            }
            set {
                this.идентТрансУпакField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        КИЗ,

        /// <remarks/>
        НомУпак,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СумНДСТип
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("БезНДС", typeof(СумНДСТипБезНДС))]
        [System.Xml.Serialization.XmlElementAttribute("СумНДС", typeof(decimal))]
        public object Item
        {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum СумНДСТипБезНДС
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("без НДС")]
        безНДС,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class РазнСумНалТип
    {

        private decimal itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СумУвел", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("СумУм", typeof(decimal))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public decimal Item
        {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        СумУвел,

        /// <remarks/>
        СумУм,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СумАкцизТип
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("БезАкциз", typeof(СумАкцизТипБезАкциз))]
        [System.Xml.Serialization.XmlElementAttribute("СумАкциз", typeof(decimal))]
        public object Item
        {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum СумАкцизТипБезАкциз
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("без акциза")]
        безакциза,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СтоимТип
    {

        private decimal стоимДоИзмField;

        private bool стоимДоИзмFieldSpecified;

        private decimal стоимПослеИзмField;

        private bool стоимПослеИзмFieldSpecified;

        private decimal стоимУвелField;

        private bool стоимУвелFieldSpecified;

        private decimal стоимУмField;

        private bool стоимУмFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтоимДоИзм
        {
            get {
                return this.стоимДоИзмField;
            }
            set {
                this.стоимДоИзмField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтоимДоИзмSpecified
        {
            get {
                return this.стоимДоИзмFieldSpecified;
            }
            set {
                this.стоимДоИзмFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтоимПослеИзм
        {
            get {
                return this.стоимПослеИзмField;
            }
            set {
                this.стоимПослеИзмField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтоимПослеИзмSpecified
        {
            get {
                return this.стоимПослеИзмFieldSpecified;
            }
            set {
                this.стоимПослеИзмFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтоимУвел
        {
            get {
                return this.стоимУвелField;
            }
            set {
                this.стоимУвелField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтоимУвелSpecified
        {
            get {
                return this.стоимУвелFieldSpecified;
            }
            set {
                this.стоимУвелFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтоимУм
        {
            get {
                return this.стоимУмField;
            }
            set {
                this.стоимУмField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтоимУмSpecified
        {
            get {
                return this.стоимУмFieldSpecified;
            }
            set {
                this.стоимУмFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТекстИнфТип
    {

        private string идентифField;

        private string значенField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Идентиф
        {
            get {
                return this.идентифField;
            }
            set {
                this.идентифField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Значен
        {
            get {
                return this.значенField;
            }
            set {
                this.значенField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class КонтактТип
    {

        private string тлфField;

        private string элПочтаField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тлф
        {
            get {
                return this.тлфField;
            }
            set {
                this.тлфField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ЭлПочта
        {
            get {
                return this.элПочтаField;
            }
            set {
                this.элПочтаField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрИнфТип
    {

        private string кодСтрField;

        private string адрТекстField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодСтр
        {
            get {
                return this.кодСтрField;
            }
            set {
                this.кодСтрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрТекст
        {
            get {
                return this.адрТекстField;
            }
            set {
                this.адрТекстField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрРФТип
    {

        private string индексField;

        private string кодРегионField;

        private string районField;

        private string городField;

        private string населПунктField;

        private string улицаField;

        private string домField;

        private string корпусField;

        private string квартField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс
        {
            get {
                return this.индексField;
            }
            set {
                this.индексField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодРегион
        {
            get {
                return this.кодРегионField;
            }
            set {
                this.кодРегионField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район
        {
            get {
                return this.районField;
            }
            set {
                this.районField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город
        {
            get {
                return this.городField;
            }
            set {
                this.городField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт
        {
            get {
                return this.населПунктField;
            }
            set {
                this.населПунктField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Улица
        {
            get {
                return this.улицаField;
            }
            set {
                this.улицаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Дом
        {
            get {
                return this.домField;
            }
            set {
                this.домField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Корпус
        {
            get {
                return this.корпусField;
            }
            set {
                this.корпусField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Кварт
        {
            get {
                return this.квартField;
            }
            set {
                this.квартField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдресТип
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрИнф", typeof(АдрИнфТип))]
        [System.Xml.Serialization.XmlElementAttribute("АдрРФ", typeof(АдрРФТип))]
        [System.Xml.Serialization.XmlElementAttribute("КодГАР", typeof(string))]
        public object Item
        {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФИОТип
    {

        private string фамилияField;

        private string имяField;

        private string отчествоField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия
        {
            get {
                return this.фамилияField;
            }
            set {
                this.фамилияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя
        {
            get {
                return this.имяField;
            }
            set {
                this.имяField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество
        {
            get {
                return this.отчествоField;
            }
            set {
                this.отчествоField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвИПТип
    {

        private ФИОТип фИОField;

        private string иННФЛField;

        private string свГосРегИПField;

        private string иныеСведField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get {
                return this.иННФЛField;
            }
            set {
                this.иННФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвГосРегИП
        {
            get {
                return this.свГосРегИПField;
            }
            set {
                this.свГосРегИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get {
                return this.иныеСведField;
            }
            set {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвПродПокТип
    {

        private СвПродПокТипИдСв идСвField;

        private АдресТип адресField;

        private КонтактТип контактField;

        private СвПродПокТипБанкРекв банкРеквField;

        private string оКПОField;

        private string структПодрField;

        private string инфДляУчастField;

        /// <remarks/>
        public СвПродПокТипИдСв ИдСв
        {
            get {
                return this.идСвField;
            }
            set {
                this.идСвField = value;
            }
        }

        /// <remarks/>
        public АдресТип Адрес
        {
            get {
                return this.адресField;
            }
            set {
                this.адресField = value;
            }
        }

        /// <remarks/>
        public КонтактТип Контакт
        {
            get {
                return this.контактField;
            }
            set {
                this.контактField = value;
            }
        }

        /// <remarks/>
        public СвПродПокТипБанкРекв БанкРекв
        {
            get {
                return this.банкРеквField;
            }
            set {
                this.банкРеквField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКПО
        {
            get {
                return this.оКПОField;
            }
            set {
                this.оКПОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СтруктПодр
        {
            get {
                return this.структПодрField;
            }
            set {
                this.структПодрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИнфДляУчаст
        {
            get {
                return this.инфДляУчастField;
            }
            set {
                this.инфДляУчастField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СвПродПокТипИдСв
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвИП", typeof(СвИПТип))]
        [System.Xml.Serialization.XmlElementAttribute("СвИнНеУч", typeof(СвПродПокТипИдСвСвИнНеУч))]
        [System.Xml.Serialization.XmlElementAttribute("СвЮЛУч", typeof(СвПродПокТипИдСвСвЮЛУч))]
        public object Item
        {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СвПродПокТипИдСвСвИнНеУч
    {

        private string наимОргField;

        private string идентифField;

        private string иныеСведField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get {
                return this.наимОргField;
            }
            set {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Идентиф
        {
            get {
                return this.идентифField;
            }
            set {
                this.идентифField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get {
                return this.иныеСведField;
            }
            set {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СвПродПокТипИдСвСвЮЛУч
    {

        private string наимОргField;

        private string иННЮЛField;

        private string кППField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get {
                return this.наимОргField;
            }
            set {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get {
                return this.иННЮЛField;
            }
            set {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП
        {
            get {
                return this.кППField;
            }
            set {
                this.кППField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СвПродПокТипБанкРекв
    {

        private СвПродПокТипБанкРеквСвБанк свБанкField;

        private string номерСчетаField;

        /// <remarks/>
        public СвПродПокТипБанкРеквСвБанк СвБанк
        {
            get {
                return this.свБанкField;
            }
            set {
                this.свБанкField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерСчета
        {
            get {
                return this.номерСчетаField;
            }
            set {
                this.номерСчетаField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СвПродПокТипБанкРеквСвБанк
    {

        private string наимБанкField;

        private string бИКField;

        private string корСчетField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимБанк
        {
            get {
                return this.наимБанкField;
            }
            set {
                this.наимБанкField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string БИК
        {
            get {
                return this.бИКField;
            }
            set {
                this.бИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КорСчет
        {
            get {
                return this.корСчетField;
            }
            set {
                this.корСчетField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокумент
    {

        private ФайлДокументСвКСчФ свКСчФField;

        private ФайлДокументТаблКСчФ таблКСчФField;

        private ФайлДокументСодФХЖ3 содФХЖ3Field;

        private ФайлДокументПодписант[] подписантField;

        private ФайлДокументКНД кНДField;

        private ФайлДокументФункция функцияField;

        private string поФактХЖField;

        private string наимДокОпрField;

        private string датаИнфПрField;

        private string времИнфПрField;

        private string наимЭконСубСостField;

        private string оснДоверОргСостField;

        /// <remarks/>
        public ФайлДокументСвКСчФ СвКСчФ
        {
            get {
                return this.свКСчФField;
            }
            set {
                this.свКСчФField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументТаблКСчФ ТаблКСчФ
        {
            get {
                return this.таблКСчФField;
            }
            set {
                this.таблКСчФField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСодФХЖ3 СодФХЖ3
        {
            get {
                return this.содФХЖ3Field;
            }
            set {
                this.содФХЖ3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Подписант")]
        public ФайлДокументПодписант[] Подписант
        {
            get {
                return this.подписантField;
            }
            set {
                this.подписантField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументКНД КНД
        {
            get {
                return this.кНДField;
            }
            set {
                this.кНДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументФункция Функция
        {
            get {
                return this.функцияField;
            }
            set {
                this.функцияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПоФактХЖ
        {
            get {
                return this.поФактХЖField;
            }
            set {
                this.поФактХЖField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДокОпр
        {
            get {
                return this.наимДокОпрField;
            }
            set {
                this.наимДокОпрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИнфПр
        {
            get {
                return this.датаИнфПрField;
            }
            set {
                this.датаИнфПрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВремИнфПр
        {
            get {
                return this.времИнфПрField;
            }
            set {
                this.времИнфПрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЭконСубСост
        {
            get {
                return this.наимЭконСубСостField;
            }
            set {
                this.наимЭконСубСостField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснДоверОргСост
        {
            get {
                return this.оснДоверОргСостField;
            }
            set {
                this.оснДоверОргСостField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвКСчФ
    {

        private ФайлДокументСвКСчФСчФ[] счФField;

        private ФайлДокументСвКСчФИспрКСчФ испрКСчФField;

        private СвПродПокТип свПродField;

        private СвПродПокТип свПокупField;

        private ФайлДокументСвКСчФДопСвФХЖ1 допСвФХЖ1Field;

        private ФайлДокументСвКСчФИнфПолФХЖ1 инфПолФХЖ1Field;

        private string номерКСчФField;

        private string датаКСчФField;

        private string кодОКВField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СчФ")]
        public ФайлДокументСвКСчФСчФ[] СчФ
        {
            get {
                return this.счФField;
            }
            set {
                this.счФField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСвКСчФИспрКСчФ ИспрКСчФ
        {
            get {
                return this.испрКСчФField;
            }
            set {
                this.испрКСчФField = value;
            }
        }

        /// <remarks/>
        public СвПродПокТип СвПрод
        {
            get {
                return this.свПродField;
            }
            set {
                this.свПродField = value;
            }
        }

        /// <remarks/>
        public СвПродПокТип СвПокуп
        {
            get {
                return this.свПокупField;
            }
            set {
                this.свПокупField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСвКСчФДопСвФХЖ1 ДопСвФХЖ1
        {
            get {
                return this.допСвФХЖ1Field;
            }
            set {
                this.допСвФХЖ1Field = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСвКСчФИнфПолФХЖ1 ИнфПолФХЖ1
        {
            get {
                return this.инфПолФХЖ1Field;
            }
            set {
                this.инфПолФХЖ1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерКСчФ
        {
            get {
                return this.номерКСчФField;
            }
            set {
                this.номерКСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаКСчФ
        {
            get {
                return this.датаКСчФField;
            }
            set {
                this.датаКСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодОКВ
        {
            get {
                return this.кодОКВField;
            }
            set {
                this.кодОКВField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвКСчФСчФ
    {

        private ФайлДокументСвКСчФСчФИспрСчФ[] испрСчФField;

        private string номерСчФField;

        private string датаСчФField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИспрСчФ")]
        public ФайлДокументСвКСчФСчФИспрСчФ[] ИспрСчФ
        {
            get {
                return this.испрСчФField;
            }
            set {
                this.испрСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерСчФ
        {
            get {
                return this.номерСчФField;
            }
            set {
                this.номерСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаСчФ
        {
            get {
                return this.датаСчФField;
            }
            set {
                this.датаСчФField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвКСчФСчФИспрСчФ
    {

        private string номИспрСчФField;

        private string датаИспрСчФField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string НомИспрСчФ
        {
            get {
                return this.номИспрСчФField;
            }
            set {
                this.номИспрСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИспрСчФ
        {
            get {
                return this.датаИспрСчФField;
            }
            set {
                this.датаИспрСчФField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвКСчФИспрКСчФ
    {

        private string номИспрКСчФField;

        private string датаИспрКСчФField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string НомИспрКСчФ
        {
            get {
                return this.номИспрКСчФField;
            }
            set {
                this.номИспрКСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИспрКСчФ
        {
            get {
                return this.датаИспрКСчФField;
            }
            set {
                this.датаИспрКСчФField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвКСчФДопСвФХЖ1
    {

        private string идГосКонField;

        private string наимОКВField;

        private decimal курсВалField;

        private bool курсВалFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдГосКон
        {
            get {
                return this.идГосКонField;
            }
            set {
                this.идГосКонField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОКВ
        {
            get {
                return this.наимОКВField;
            }
            set {
                this.наимОКВField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КурсВал
        {
            get {
                return this.курсВалField;
            }
            set {
                this.курсВалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КурсВалSpecified
        {
            get {
                return this.курсВалFieldSpecified;
            }
            set {
                this.курсВалFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвКСчФИнфПолФХЖ1
    {

        private ТекстИнфТип[] текстИнфField;

        private string идФайлИнфПолField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТекстИнф")]
        public ТекстИнфТип[] ТекстИнф
        {
            get {
                return this.текстИнфField;
            }
            set {
                this.текстИнфField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайлИнфПол
        {
            get {
                return this.идФайлИнфПолField;
            }
            set {
                this.идФайлИнфПолField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблКСчФ
    {

        private ФайлДокументТаблКСчФСведТов[] сведТовField;

        private ФайлДокументТаблКСчФВсегоУвел всегоУвелField;

        private ФайлДокументТаблКСчФВсегоУм всегоУмField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведТов")]
        public ФайлДокументТаблКСчФСведТов[] СведТов
        {
            get {
                return this.сведТовField;
            }
            set {
                this.сведТовField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументТаблКСчФВсегоУвел ВсегоУвел
        {
            get {
                return this.всегоУвелField;
            }
            set {
                this.всегоУвелField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументТаблКСчФВсегоУм ВсегоУм
        {
            get {
                return this.всегоУмField;
            }
            set {
                this.всегоУмField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблКСчФСведТов
    {

        private СтоимТип стТовБезНДСField;

        private СумАкцизТип акцизДоField;

        private СумАкцизТип акцизПослеField;

        private РазнСумНалТип акцизРазнField;

        private СумНДСТип сумНалДоField;

        private СумНДСТип сумНалПослеField;

        private РазнСумНалТип сумНалРазнField;

        private СтоимТип стТовУчНалField;

        private ФайлДокументТаблКСчФСведТовИнфПолФХЖ2[] инфПолФХЖ2Field;

        private ФайлДокументТаблКСчФСведТовДопСведТов допСведТовField;

        private ФайлДокументТаблКСчФСведТовСведПрослеж[] сведПрослежField;

        private НомСредИдТовТип[] номСредИдентТовДоField;

        private НомСредИдТовТип[] номСредИдентТовПослеField;

        private string номСтрField;

        private string порНомТовВСЧФField;

        private string наимТовField;

        private string оКЕИ_ТовДоField;

        private string оКЕИ_ТовПослеField;

        private decimal колТовДоField;

        private bool колТовДоFieldSpecified;

        private decimal колТовПослеField;

        private bool колТовПослеFieldSpecified;

        private decimal ценаТовДоField;

        private bool ценаТовДоFieldSpecified;

        private decimal ценаТовПослеField;

        private bool ценаТовПослеFieldSpecified;

        private ФайлДокументТаблКСчФСведТовНалСтДо налСтДоField;

        private ФайлДокументТаблКСчФСведТовНалСтПосле налСтПослеField;

        /// <remarks/>
        public СтоимТип СтТовБезНДС
        {
            get {
                return this.стТовБезНДСField;
            }
            set {
                this.стТовБезНДСField = value;
            }
        }

        /// <remarks/>
        public СумАкцизТип АкцизДо
        {
            get {
                return this.акцизДоField;
            }
            set {
                this.акцизДоField = value;
            }
        }

        /// <remarks/>
        public СумАкцизТип АкцизПосле
        {
            get {
                return this.акцизПослеField;
            }
            set {
                this.акцизПослеField = value;
            }
        }

        /// <remarks/>
        public РазнСумНалТип АкцизРазн
        {
            get {
                return this.акцизРазнField;
            }
            set {
                this.акцизРазнField = value;
            }
        }

        /// <remarks/>
        public СумНДСТип СумНалДо
        {
            get {
                return this.сумНалДоField;
            }
            set {
                this.сумНалДоField = value;
            }
        }

        /// <remarks/>
        public СумНДСТип СумНалПосле
        {
            get {
                return this.сумНалПослеField;
            }
            set {
                this.сумНалПослеField = value;
            }
        }

        /// <remarks/>
        public РазнСумНалТип СумНалРазн
        {
            get {
                return this.сумНалРазнField;
            }
            set {
                this.сумНалРазнField = value;
            }
        }

        /// <remarks/>
        public СтоимТип СтТовУчНал
        {
            get {
                return this.стТовУчНалField;
            }
            set {
                this.стТовУчНалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнфПолФХЖ2")]
        public ФайлДокументТаблКСчФСведТовИнфПолФХЖ2[] ИнфПолФХЖ2
        {
            get {
                return this.инфПолФХЖ2Field;
            }
            set {
                this.инфПолФХЖ2Field = value;
            }
        }

        /// <remarks/>
        public ФайлДокументТаблКСчФСведТовДопСведТов ДопСведТов
        {
            get {
                return this.допСведТовField;
            }
            set {
                this.допСведТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведПрослеж")]
        public ФайлДокументТаблКСчФСведТовСведПрослеж[] СведПрослеж
        {
            get {
                return this.сведПрослежField;
            }
            set {
                this.сведПрослежField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НомСредИдентТовДо")]
        public НомСредИдТовТип[] НомСредИдентТовДо
        {
            get {
                return this.номСредИдентТовДоField;
            }
            set {
                this.номСредИдентТовДоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НомСредИдентТовПосле")]
        public НомСредИдТовТип[] НомСредИдентТовПосле
        {
            get {
                return this.номСредИдентТовПослеField;
            }
            set {
                this.номСредИдентТовПослеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string НомСтр
        {
            get {
                return this.номСтрField;
            }
            set {
                this.номСтрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string ПорНомТовВСЧФ
        {
            get {
                return this.порНомТовВСЧФField;
            }
            set {
                this.порНомТовВСЧФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимТов
        {
            get {
                return this.наимТовField;
            }
            set {
                this.наимТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКЕИ_ТовДо
        {
            get {
                return this.оКЕИ_ТовДоField;
            }
            set {
                this.оКЕИ_ТовДоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКЕИ_ТовПосле
        {
            get {
                return this.оКЕИ_ТовПослеField;
            }
            set {
                this.оКЕИ_ТовПослеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КолТовДо
        {
            get {
                return this.колТовДоField;
            }
            set {
                this.колТовДоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КолТовДоSpecified
        {
            get {
                return this.колТовДоFieldSpecified;
            }
            set {
                this.колТовДоFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КолТовПосле
        {
            get {
                return this.колТовПослеField;
            }
            set {
                this.колТовПослеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КолТовПослеSpecified
        {
            get {
                return this.колТовПослеFieldSpecified;
            }
            set {
                this.колТовПослеFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ЦенаТовДо
        {
            get {
                return this.ценаТовДоField;
            }
            set {
                this.ценаТовДоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ЦенаТовДоSpecified
        {
            get {
                return this.ценаТовДоFieldSpecified;
            }
            set {
                this.ценаТовДоFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ЦенаТовПосле
        {
            get {
                return this.ценаТовПослеField;
            }
            set {
                this.ценаТовПослеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ЦенаТовПослеSpecified
        {
            get {
                return this.ценаТовПослеFieldSpecified;
            }
            set {
                this.ценаТовПослеFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументТаблКСчФСведТовНалСтДо НалСтДо
        {
            get {
                return this.налСтДоField;
            }
            set {
                this.налСтДоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументТаблКСчФСведТовНалСтПосле НалСтПосле
        {
            get {
                return this.налСтПослеField;
            }
            set {
                this.налСтПослеField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблКСчФСведТовИнфПолФХЖ2
    {

        private string идентифField;

        private string значенField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Идентиф
        {
            get {
                return this.идентифField;
            }
            set {
                this.идентифField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Значен
        {
            get {
                return this.значенField;
            }
            set {
                this.значенField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблКСчФСведТовДопСведТов
    {

        private string характерТовField;

        private string сортТовField;

        private string артикулТовField;

        private string кодТовField;

        private string наимЕдИзмДоField;

        private string наимЕдИзмПослеField;

        private string кодВидТовField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ХарактерТов
        {
            get {
                return this.характерТовField;
            }
            set {
                this.характерТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СортТов
        {
            get {
                return this.сортТовField;
            }
            set {
                this.сортТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АртикулТов
        {
            get {
                return this.артикулТовField;
            }
            set {
                this.артикулТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодТов
        {
            get {
                return this.кодТовField;
            }
            set {
                this.кодТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЕдИзмДо
        {
            get {
                return this.наимЕдИзмДоField;
            }
            set {
                this.наимЕдИзмДоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЕдИзмПосле
        {
            get {
                return this.наимЕдИзмПослеField;
            }
            set {
                this.наимЕдИзмПослеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодВидТов
        {
            get {
                return this.кодВидТовField;
            }
            set {
                this.кодВидТовField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблКСчФСведТовСведПрослеж
    {

        private ФайлДокументТаблКСчФСведТовСведПрослежИзмКолЕдПТ измКолЕдПТField;

        private string номТовПрослежField;

        private string едИзмПрослежField;

        private string допПрослежField;

        /// <remarks/>
        public ФайлДокументТаблКСчФСведТовСведПрослежИзмКолЕдПТ ИзмКолЕдПТ
        {
            get {
                return this.измКолЕдПТField;
            }
            set {
                this.измКолЕдПТField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомТовПрослеж
        {
            get {
                return this.номТовПрослежField;
            }
            set {
                this.номТовПрослежField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ЕдИзмПрослеж
        {
            get {
                return this.едИзмПрослежField;
            }
            set {
                this.едИзмПрослежField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДопПрослеж
        {
            get {
                return this.допПрослежField;
            }
            set {
                this.допПрослежField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблКСчФСведТовСведПрослежИзмКолЕдПТ
    {

        private decimal itemField;

        private ItemChoiceType1 itemElementNameField;

        private decimal колТовЕдПТДоField;

        private decimal колТовЕдПТПослеField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КолТовЕдПТУвел", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("КолТовЕдПТУм", typeof(decimal))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public decimal Item
        {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName
        {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КолТовЕдПТДо
        {
            get {
                return this.колТовЕдПТДоField;
            }
            set {
                this.колТовЕдПТДоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КолТовЕдПТПосле
        {
            get {
                return this.колТовЕдПТПослеField;
            }
            set {
                this.колТовЕдПТПослеField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        КолТовЕдПТУвел,

        /// <remarks/>
        КолТовЕдПТУм,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументТаблКСчФСведТовНалСтДо
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0%")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10%")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18%")]
        Item18,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20%")]
        Item20,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10/110")]
        Item10110,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18/118")]
        Item18118,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20/120")]
        Item20120,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("без НДС")]
        безНДС,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("НДС исчисляется налоговым агентом")]
        НДСисчисляетсяналоговымагентом,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументТаблКСчФСведТовНалСтПосле
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0%")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10%")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18%")]
        Item18,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20%")]
        Item20,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10/110")]
        Item10110,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18/118")]
        Item18118,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20/120")]
        Item20120,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("без НДС")]
        безНДС,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("НДС исчисляется налоговым агентом")]
        НДСисчисляетсяналоговымагентом,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблКСчФВсегоУвел
    {

        private СумНДСТип сумНалField;

        private decimal стТовБезНДСВсегоField;

        private decimal стТовУчНалВсегоField;

        private bool стТовУчНалВсегоFieldSpecified;

        /// <remarks/>
        public СумНДСТип СумНал
        {
            get {
                return this.сумНалField;
            }
            set {
                this.сумНалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовБезНДСВсего
        {
            get {
                return this.стТовБезНДСВсегоField;
            }
            set {
                this.стТовБезНДСВсегоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовУчНалВсего
        {
            get {
                return this.стТовУчНалВсегоField;
            }
            set {
                this.стТовУчНалВсегоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовУчНалВсегоSpecified
        {
            get {
                return this.стТовУчНалВсегоFieldSpecified;
            }
            set {
                this.стТовУчНалВсегоFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблКСчФВсегоУм
    {

        private СумНДСТип сумНалField;

        private decimal стТовБезНДСВсегоField;

        private decimal стТовУчНалВсегоField;

        private bool стТовУчНалВсегоFieldSpecified;

        /// <remarks/>
        public СумНДСТип СумНал
        {
            get {
                return this.сумНалField;
            }
            set {
                this.сумНалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовБезНДСВсего
        {
            get {
                return this.стТовБезНДСВсегоField;
            }
            set {
                this.стТовБезНДСВсегоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовУчНалВсего
        {
            get {
                return this.стТовУчНалВсегоField;
            }
            set {
                this.стТовУчНалВсегоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовУчНалВсегоSpecified
        {
            get {
                return this.стТовУчНалВсегоFieldSpecified;
            }
            set {
                this.стТовУчНалВсегоFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ3
    {

        private ДокумТип[] передатДокумField;

        private ДокумТип[] докумОснКорField;

        private string иныеСвИзмСтоимField;

        private string содОперField;

        private string датаНапрField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПередатДокум")]
        public ДокумТип[] ПередатДокум
        {
            get {
                return this.передатДокумField;
            }
            set {
                this.передатДокумField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДокумОснКор")]
        public ДокумТип[] ДокумОснКор
        {
            get {
                return this.докумОснКорField;
            }
            set {
                this.докумОснКорField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвИзмСтоим
        {
            get {
                return this.иныеСвИзмСтоимField;
            }
            set {
                this.иныеСвИзмСтоимField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СодОпер
        {
            get {
                return this.содОперField;
            }
            set {
                this.содОперField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаНапр
        {
            get {
                return this.датаНапрField;
            }
            set {
                this.датаНапрField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписант
    {

        private object itemField;

        private ФайлДокументПодписантОблПолн облПолнField;

        private ФайлДокументПодписантСтатус статусField;

        private string оснПолнField;

        private string оснПолнОргField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИП", typeof(СвИПТип))]
        [System.Xml.Serialization.XmlElementAttribute("ФЛ", typeof(ФайлДокументПодписантФЛ))]
        [System.Xml.Serialization.XmlElementAttribute("ЮЛ", typeof(ФайлДокументПодписантЮЛ))]
        public object Item
        {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументПодписантОблПолн ОблПолн
        {
            get {
                return this.облПолнField;
            }
            set {
                this.облПолнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументПодписантСтатус Статус
        {
            get {
                return this.статусField;
            }
            set {
                this.статусField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолн
        {
            get {
                return this.оснПолнField;
            }
            set {
                this.оснПолнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолнОрг
        {
            get {
                return this.оснПолнОргField;
            }
            set {
                this.оснПолнОргField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписантФЛ
    {

        private ФИОТип фИОField;

        private string госРегИППодпField;

        private string иННФЛField;

        private string иныеСведField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ГосРегИППодп
        {
            get {
                return this.госРегИППодпField;
            }
            set {
                this.госРегИППодпField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get {
                return this.иННФЛField;
            }
            set {
                this.иННФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get {
                return this.иныеСведField;
            }
            set {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписантЮЛ
    {

        private ФИОТип фИОField;

        private string госРегИППодпField;

        private string иННЮЛField;

        private string наимОргField;

        private string должнField;

        private string иныеСведField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ГосРегИППодп
        {
            get {
                return this.госРегИППодпField;
            }
            set {
                this.госРегИППодпField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get {
                return this.иННЮЛField;
            }
            set {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get {
                return this.наимОргField;
            }
            set {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должн
        {
            get {
                return this.должнField;
            }
            set {
                this.должнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get {
                return this.иныеСведField;
            }
            set {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументПодписантОблПолн
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументПодписантСтатус
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументКНД
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1115133")]
        Item1115133,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументФункция
    {

        /// <remarks/>
        КСЧФ,

        /// <remarks/>
        КСЧФДИС,

        /// <remarks/>
        ДИС,

        /// <remarks/>
        СвИСРК,

        /// <remarks/>
        СвИСЗК,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлВерсФорм
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.01")]
        Item501,
    }
}