//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystems.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://markirovka.crpt.ru/api/v3/true-api")]
        public string UrlAddressHonestMark {
            get {
                return ((string)(this["UrlAddressHonestMark"]));
            }
            set {
                this["UrlAddressHonestMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://edo-gismt.crpt.ru")]
        public string UrlAddressEdoLite {
            get {
                return ((string)(this["UrlAddressEdoLite"]));
            }
            set {
                this["UrlAddressEdoLite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://diadoc-api.kontur.ru")]
        public string DiadocApiUrl {
            get {
                return ((string)(this["DiadocApiUrl"]));
            }
            set {
                this["DiadocApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.20")]
        public string DbWebIpAddress {
            get {
                return ((string)(this["DbWebIpAddress"]));
            }
            set {
                this["DbWebIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://suzgrid.crpt.ru")]
        public string UrlAddressOrderManagmentStation {
            get {
                return ((string)(this["UrlAddressOrderManagmentStation"]));
            }
            set {
                this["UrlAddressOrderManagmentStation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://markirovka.crpt.ru/api/v4/true-api")]
        public string UrlAddressHonestMarkNewVersion {
            get {
                return ((string)(this["UrlAddressHonestMarkNewVersion"]));
            }
            set {
                this["UrlAddressHonestMarkNewVersion"] = value;
            }
        }
    }
}
